# -*- coding: utf-8 -*-
"""Build 海之家 DZMM local shell: copy engine, inject Dzmm plugins, pack img/audio zip.

- publish/ keeps engine + data + plugins only (<400 files)
- img/ + audio/ → publish/game-pack.zip
- default packMode=r2（yodu 桶）；?pack=local 回本地 zip
"""
from __future__ import annotations

import json
import re
import shutil
import zipfile
from pathlib import Path

SRC = Path(r"d:\云端本地开发\游戏\海之家")
DST = Path(r"d:\云端本地开发\游戏\海之家-dzmm")
PUB = DST / "publish"
NATSU_PLUG = Path(r"d:\云端本地开发\游戏\natsu-ntr-friend-gf-dzmm\publish\js\plugins")
JSZIP_SRC = Path(r"d:\云端本地开发\jk少女\publish\js\libs\jszip.min.js")

DZMM_PLUGINS = [
    "DzmmSeCache",
    "DzmmSafeStorage",
    "DzmmBootFont",
    "DzmmSafeLoading",
    "DzmmAutoStretch",
    "DzmmTouchUi",
    "DzmmPlatformSave",
    "DzmmKeyboardName",
]

SHELL_COPY = [
    "css",
    "data",
    "icon",
    "js",
    "translations.json",
]

CACHE_TAG = "umi260908h"


def copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def patch_plugins_js(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"=\s*(\[.*\])\s*;?\s*$", text, re.S)
    if not m:
        raise SystemExit("plugins.js parse failed")
    arr = json.loads(m.group(1))
    # drop any prior Dzmm*
    arr = [p for p in arr if not str(p.get("name", "")).startswith("Dzmm")]
    head = [
        {"name": n, "status": True, "description": "DZMM", "parameters": {}}
        for n in DZMM_PLUGINS
    ]
    merged = head + arr
    # 不改 PictureSpine / SkipTitle 等原作参数（与源 plugins.js 一致）
    name = chr(36) + "plugins"  # avoid PowerShell eating $plugins in -c scripts
    out = (
        "// Generated by RPG Maker.\n"
        "// Do not edit this file directly.\n"
        "var "
        + name
        + " =\n"
        + json.dumps(merged, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    path.write_text(out, encoding="utf-8")
    print("plugins.js", len(merged), "entries (+", len(DZMM_PLUGINS), "Dzmm)")


def write_index(src_html: Path, dst_html: Path) -> None:
    html = src_html.read_text(encoding="utf-8")
    # drop external mcy helpers
    html = re.sub(
        r'\s*<script[^>]+src="https://js\.mcy520\.cfd/[^"]+"[^>]*>\s*</script>',
        "",
        html,
        flags=re.I,
    )
    inject = (
        f'\n        <script type="text/javascript" src="js/libs/jszip.min.js"></script>\n'
        f'        <script type="text/javascript" src="asset-cdn.js?v={CACHE_TAG}"></script>\n'
        f'        <script type="text/javascript" src="js/main.js"></script>\n'
    )
    html = re.sub(
        r'\s*<script[^>]+src=["\']js/main\.js["\'][^>]*>\s*</script>\s*',
        inject,
        html,
        count=1,
        flags=re.I,
    )
    # title keep
    dst_html.write_text(html, encoding="utf-8")
    print("index.html written")


def write_asset_cdn(path: Path) -> None:
    path.write_text(
        f"""/**
 * 海之家 / ウミノイエ — 重资源走 game-pack.zip
 * 默认 R2；本地调试用 ?pack=local。
 *
 *   ?pack=r2    → R2（默认）
 *   ?pack=local → publish/game-pack.zip
 *   ?pack=0     → 散文件（本地需有 img/audio，或以后 CDN）
 *   ?cdn=0      → 纯磁盘，不改写 URL
 */
(function () {{
  "use strict";

  var CDN = "https://pub-db5421ea70f04d5e8caa7e9a211e381c.r2.dev/umi-no-ie/";
  var CACHE_TAG = "{CACHE_TAG}";
  var PACK_URL_R2 = CDN + "game-pack.zip?v=" + CACHE_TAG;
  var PACK_URL_LOCAL = "game-pack.zip?v=" + CACHE_TAG;
  var qs = location.search || "";
  var forceLocal = /(?:^|[?&])cdn=0(?:&|$)/.test(qs);
  var USE_CDN = !forceLocal;
  var packMode = "r2";
  if (/(?:^|[?&])pack=0(?:&|$)/.test(qs)) packMode = "off";
  else if (/(?:^|[?&])pack=local(?:&|$)/.test(qs)) packMode = "local";
  else if (/(?:^|[?&])pack=r2(?:&|$)/.test(qs)) packMode = "r2";
  var USE_PACK = USE_CDN && packMode !== "off";
  var PACK_URL = packMode === "local" ? PACK_URL_LOCAL : PACK_URL_R2;

  var PREFIXES = ["img/", "audio/", "fonts/"];
  // Boot 关键留壳；spines 进 pack
  var LOCAL_PREFIXES = ["img/system/", "fonts/"];
  var packBlobs = Object.create(null);
  var packUrls = Object.create(null);
  var progressListeners = [];

  function emitProgress(info) {{
    for (var i = 0; i < progressListeners.length; i++) {{
      try {{ progressListeners[i](info); }} catch (e) {{}}
    }}
    try {{
      if (window.dzmm && dzmm.loading && typeof dzmm.loading.progress === "function") {{
        dzmm.loading.progress({{
          phase: info.phase === "done" ? "boot" : "assets",
          message: info.message || "",
          current: info.current || 0,
          total: info.total || 0
        }});
      }}
    }} catch (e) {{}}
  }}

  function encodeRelPath(rel) {{
    rel = String(rel || "").replace(/^\\.\\//, "");
    return rel.split("/").map(function (seg) {{
      if (!seg) return seg;
      try {{ return encodeURIComponent(decodeURIComponent(seg)); }}
      catch (e) {{ return encodeURIComponent(seg); }}
    }}).join("/");
  }}

  function stripBase(pathname) {{
    var path = String(pathname || "");
    try {{
      var base = location.pathname.replace(/\\/[^/]*$/, "/");
      if (path.indexOf(base) === 0) path = path.slice(base.length);
    }} catch (e) {{}}
    return path.replace(/^\\//, "").replace(/^static\\//, "");
  }}

  function isLocalAsset(rel) {{
    rel = String(rel || "");
    for (var i = 0; i < LOCAL_PREFIXES.length; i++) {{
      if (rel.indexOf(LOCAL_PREFIXES[i]) === 0) return true;
    }}
    return false;
  }}

  function shouldMapRel(rel) {{
    if (!rel || isLocalAsset(rel)) return false;
    for (var i = 0; i < PREFIXES.length; i++) {{
      if (rel.indexOf(PREFIXES[i]) === 0) return true;
    }}
    return false;
  }}

  function relFromUrl(url) {{
    if (!url) return "";
    var s = String(url);
    if (/^(?:blob:|data:)/i.test(s)) return "";
    if (s.indexOf(CDN) === 0) s = s.slice(CDN.length);
    else if (/^(?:https?:)/i.test(s)) {{
      try {{
        var u = new URL(s, location.href);
        if (u.origin !== location.origin && s.indexOf(CDN) !== 0) return "";
        s = u.pathname.replace(/^\\/static\\//, "/");
      }} catch (e) {{ return ""; }}
    }}
    return stripBase(s).replace(/^\\.\\//, "");
  }}

  function blobUrl(rel) {{
    if (!packUrls[rel] && packBlobs[rel]) {{
      packUrls[rel] = URL.createObjectURL(packBlobs[rel]);
    }}
    return packUrls[rel] || "";
  }}

  function mapUrl(url) {{
    if (!USE_CDN || !url) return url;
    if (/^(?:blob:|data:)/i.test(String(url))) return url;
    var rel = relFromUrl(url);
    if (!shouldMapRel(rel)) return url;
    var pathOnly = rel.split("#")[0].split("?")[0];
    var packed = blobUrl(pathOnly);
    if (packed) return packed;
    if (String(url).indexOf(CDN) === 0) return url;
    // no R2 yet: keep relative (will 404 unless ?cdn=0 with disk files)
    return url;
  }}

  function formatMB(n) {{
    return (n / 1024 / 1024).toFixed(1);
  }}

  function downloadPack() {{
    emitProgress({{ phase: "download", message: "加载资源包…", current: 0, total: 0, ratio: 0 }});
    return new Promise(function (resolve, reject) {{
      var xhr = new XMLHttpRequest();
      xhr.open("GET", PACK_URL, true);
      xhr.responseType = "arraybuffer";
      xhr.onprogress = function (ev) {{
        var total = ev.lengthComputable ? ev.total : 0;
        emitProgress({{
          phase: "download",
          message: total
            ? "加载资源包 " + formatMB(ev.loaded) + " / " + formatMB(total) + " MB"
            : "加载资源包 " + formatMB(ev.loaded) + " MB…",
          current: ev.loaded,
          total: total,
          ratio: total ? ev.loaded / total : 0
        }});
      }};
      xhr.onload = function () {{
        if (xhr.status >= 200 && xhr.status < 300) {{
          emitProgress({{ phase: "download", message: "下载完成", current: 1, total: 1, ratio: 1 }});
          resolve(xhr.response);
        }} else reject(new Error("pack HTTP " + xhr.status));
      }};
      xhr.onerror = function () {{ reject(new Error("pack network error")); }};
      xhr.send();
    }});
  }}

  function unzipPack(buf) {{
    if (typeof JSZip === "undefined") return Promise.reject(new Error("JSZip missing"));
    emitProgress({{ phase: "unzip", message: "解压资源包…", current: 0, total: 0, ratio: 0 }});
    return JSZip.loadAsync(buf).then(function (zip) {{
      var entries = [];
      zip.forEach(function (path, file) {{
        if (!path || file.dir) return;
        entries.push({{ path: path.replace(/^\\/+/, ""), file: file }});
      }});
      var total = entries.length;
      var done = 0;
      var lastEmit = 0;
      var CONCURRENCY = 24;
      function maybeEmit(force) {{
        var now = Date.now();
        if (!force && now - lastEmit < 80 && done < total) return;
        lastEmit = now;
        emitProgress({{
          phase: "unzip",
          message: "解压资源 " + done + " / " + total,
          current: done,
          total: total,
          ratio: total ? done / total : 0
        }});
      }}
      var idx = 0;
      function pump() {{
        if (idx >= total) return Promise.resolve();
        var batch = [];
        while (batch.length < CONCURRENCY && idx < total) {{
          (function (entry) {{
            batch.push(entry.file.async("arraybuffer").then(function (ab) {{
              packBlobs[entry.path] = new Blob([ab]);
              done += 1;
              maybeEmit(false);
            }}));
          }})(entries[idx++]);
        }}
        return Promise.all(batch).then(pump);
      }}
      return pump().then(function () {{
        maybeEmit(true);
        emitProgress({{ phase: "boot", message: "正在启动游戏…", current: 1, total: 1, ratio: 1 }});
        console.info("[umi-cdn] pack ready", total, "files");
        return true;
      }});
    }});
  }}

  function loadPack() {{
    if (!USE_PACK) return Promise.resolve(false);
    return downloadPack().then(unzipPack).catch(function (e) {{
      console.warn("[umi-cdn] pack failed", e);
      emitProgress({{ phase: "error", message: "资源包加载失败", current: 0, total: 0, ratio: 0 }});
      return false;
    }});
  }}

  var packReady = USE_CDN
    ? new Promise(function (resolve) {{
        setTimeout(function () {{
          loadPack().then(resolve, function () {{ resolve(false); }});
        }}, 0);
      }})
    : Promise.resolve(false);

  window.__UMI_CDN = {{
    enabled: USE_CDN,
    base: CDN,
    tag: CACHE_TAG,
    packMode: packMode,
    packUrl: PACK_URL,
    resolve: mapUrl,
    ready: packReady,
    onProgress: function (fn) {{ if (typeof fn === "function") progressListeners.push(fn); }}
  }};

  if (!USE_CDN) {{
    console.info("[umi-cdn] LOCAL assets (?cdn=0)");
    return;
  }}

  function installLoadHooks() {{
    if (typeof Bitmap !== "undefined" && Bitmap.prototype && !Bitmap.prototype._startLoading.__umiWrapped) {{
      var _bmpLoad = Bitmap.prototype._startLoading;
      Bitmap.prototype._startLoading = function () {{
        if (this._url) this._url = mapUrl(this._url);
        return _bmpLoad.apply(this, arguments);
      }};
      Bitmap.prototype._startLoading.__umiWrapped = true;
    }}
    if (typeof WebAudio !== "undefined" && WebAudio.prototype && WebAudio.prototype._realUrl && !WebAudio.prototype._realUrl.__umiWrapped) {{
      var _real = WebAudio.prototype._realUrl;
      WebAudio.prototype._realUrl = function () {{
        return mapUrl(_real.apply(this, arguments));
      }};
      WebAudio.prototype._realUrl.__umiWrapped = true;
    }}
    if (typeof Graphics !== "undefined") {{
      wrapProto(Graphics, "setLoadingImage", mapUrl);
    }}
    return true;
  }}

  function wrapProto(obj, method, mapper) {{
    if (!obj || !obj[method] || obj[method].__umiWrapped) return;
    var orig = obj[method];
    function wrapped() {{
      var args = Array.prototype.slice.call(arguments);
      if (typeof args[0] === "string") args[0] = mapper(args[0]);
      return orig.apply(this, args);
    }}
    wrapped.__umiWrapped = true;
    obj[method] = wrapped;
  }}

  function hookTransport() {{
    if (window.__umiCdnTransportHooked) return;
    window.__umiCdnTransportHooked = true;
    var _open = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function (method, url) {{
      var args = Array.prototype.slice.call(arguments);
      if (typeof args[1] === "string") args[1] = mapUrl(args[1]);
      return _open.apply(this, args);
    }};
    if (window.fetch) {{
      var _fetch = window.fetch.bind(window);
      window.fetch = function (input, init) {{
        if (typeof input === "string") return _fetch(mapUrl(input), init);
        if (input && typeof Request !== "undefined" && input instanceof Request) {{
          var mapped = mapUrl(input.url);
          if (mapped !== input.url) return _fetch(new Request(mapped, input), init);
        }}
        return _fetch(input, init);
      }};
    }}
    try {{
      var desc = Object.getOwnPropertyDescriptor(HTMLImageElement.prototype, "src");
      if (desc && desc.set) {{
        Object.defineProperty(HTMLImageElement.prototype, "src", {{
          configurable: true,
          enumerable: true,
          get: desc.get,
          set: function (v) {{ desc.set.call(this, mapUrl(v)); }}
        }});
      }}
    }} catch (e) {{}}
  }}

  function hookSceneManager() {{
    if (typeof SceneManager === "undefined" || SceneManager.__umiCdnHooked) return false;
    SceneManager.__umiCdnHooked = true;
    var _run = SceneManager.run;
    SceneManager.run = function (sceneClass) {{
      installLoadHooks();
      var self = this;
      var args = arguments;
      return packReady.then(function () {{
        installLoadHooks();
        return _run.apply(self, args);
      }});
    }};
    return true;
  }}

  hookTransport();
  var tries = 0;
  var logged = false;
  (function wait() {{
    hookSceneManager();
    if (installLoadHooks() && !logged) {{
      logged = true;
      console.info("[umi-cdn] packMode=", packMode, "url=", PACK_URL);
    }}
    if (tries > 600) return;
    tries += 1;
    setTimeout(wait, 50);
  }})();
}})();
""",
        encoding="utf-8",
    )
    print("asset-cdn.js")


def pack_zip() -> None:
    out = PUB / "game-pack.zip"
    files: list[tuple[Path, str]] = []
    skip_prefix = ("img/system/", "fonts/")  # spines 进 pack（先压缩）
    store_ext = {".png", ".jpg", ".jpeg", ".webp", ".ogg", ".m4a", ".mp3", ".wav", ".ttf", ".otf", ".woff", ".woff2"}
    for root in ("img", "audio", "fonts"):
        base = SRC / root
        if not base.is_dir():
            continue
        for f in base.rglob("*"):
            if not f.is_file():
                continue
            if f.name.endswith(".ja.png"):
                continue
            rel = f.relative_to(SRC).as_posix()
            if any(rel.startswith(p) for p in skip_prefix):
                continue
            files.append((f, rel))
    if out.exists():
        out.unlink()
    with zipfile.ZipFile(out, "w") as zf:
        for local, key in files:
            ext = local.suffix.lower()
            comp = zipfile.ZIP_STORED if ext in store_ext else zipfile.ZIP_DEFLATED
            zf.write(local, key, compress_type=comp)
    print(f"game-pack.zip files={len(files)} size={out.stat().st_size/1e6:.1f}MB")


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    if PUB.exists():
        shutil.rmtree(PUB)
    PUB.mkdir(parents=True)

    for name in SHELL_COPY:
        src = SRC / name
        dst = PUB / name
        if src.is_dir():
            copy_tree(src, dst)
        elif src.is_file():
            shutil.copy2(src, dst)

    # Dzmm plugins
    plug_dst = PUB / "js" / "plugins"
    plug_dst.mkdir(parents=True, exist_ok=True)
    for n in DZMM_PLUGINS:
        src = NATSU_PLUG / f"{n}.js"
        if not src.is_file():
            raise SystemExit(f"missing {src}")
        shutil.copy2(src, plug_dst / f"{n}.js")

    # jszip
    shutil.copy2(JSZIP_SRC, PUB / "js" / "libs" / "jszip.min.js")

    patch_plugins_js(PUB / "js" / "plugins.js")
    # Boot 关键留壳；spines 走 pack（compress_pack_spines.py）
    for rel in ("img/system", "fonts"):
        src = SRC / rel
        dst = PUB / rel
        if src.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
    write_index(SRC / "index.html", PUB / "index.html")
    write_asset_cdn(PUB / "asset-cdn.js")
    pack_zip()

    (DST / "_sync_skip.txt").write_text(
        "publish/game-pack.zip\n"
        "# img/audio 在包内，勿散 sync\n",
        encoding="utf-8",
    )
    (DST / "说明.txt").write_text(
        "海之家 / ウミノイエ — DZMM 壳\n"
        "引擎：RPG Maker MZ（未加密）\n"
        "壳：publish/（js/data/css/plugins + img/system + fonts + img/spines）\n"
        "重资源：publish/game-pack.zip（其余 img+audio；spines 对齐 ntr live2d 留壳）\n"
        "本地预览：python -m http.server → ?pack=local；平台存档需 DZMM 预览桥\n"
        "尚未上 R2；勿 sync 容器直到用户要求\n",
        encoding="utf-8",
    )

    # file count gate
    files = [f for f in PUB.rglob("*") if f.is_file()]
    shell = [f for f in files if f.name != "game-pack.zip"]
    print("publish files", len(files), "shell_without_zip", len(shell))
    if len(shell) > 400:
        raise SystemExit(f"shell file count {len(shell)} > 400")


if __name__ == "__main__":
    main()
